#!/bin/bash

X=$(git remote -v | grep github.com | grep '(push)' | awk '{print $1 " " $2}')
if [ $(echo "$X" | wc -l) = 0 ]
then
  echo "This isn't a GitHub repository." >&2
  exit 1
fi
if [ $(echo "$X" | wc -l) -gt 1 ]
then
  if [ $# -lt 1 ]
  then
    REMOTE=origin
  else
    REMOTE=$1
  fi
  if [ $(echo "$X" | grep "^$REMOTE " | wc -l) != 1 ]
  then
    echo "Can't detect one repository." >&2
    exit 1
  else
    X=$(echo "$X" | grep "^$REMOTE ")
  fi
fi
X=$(echo $X | awk '{print $2}')
if echo $X | grep @
then
  OWNER=$(echo $X | cut -d ':' -f 2 | cut -d '/' -f 1)
  REPOS=$(echo $X | cut -d '/' -f 2 | awk -F '.git ' '{print $1}')
else
  OWNER=$(echo $X | awk -F '//' '{print $2}' | cut -d '/' -f 2)
  REPOS_WITH_EXT=$(echo $X | awk -F '//' '{print $2}' | cut -d '/' -f 3)
  REPOS=${REPOS_WITH_EXT%.*}
fi

if which sw_vers > /dev/null
then
  open https://github.com/${OWNER}/${REPOS}
else
  xdg-open https://github.com/${OWNER}/${REPOS}
fi
